Get-AppxPackage -allusers *alarm* | Remove-AppxPackage
Get-AppxPackage -allusers *camera* | Remove-AppxPackage
Get-AppxPackage -allusers *help* | Remove-AppxPackage
Get-AppxPackage -allusers *reality* | Remove-AppxPackage
Get-AppxPackage -allusers *weather* | Remove-AppxPackage
Get-AppxPackage -allusers *3D* | Remove-AppxPackage
Get-AppxPackage -allusers *Xbox* | Remove-AppxPackage
Get-AppxPackage -allusers *BingNews* | Remove-AppxPackage
Get-AppxPackage -allusers *Zune* | Remove-AppxPackage
Get-AppxPackage -allusers *Community* | Remove-AppxPackage
Get-AppxPackage -allusers *WindowsCommunicationsapps* | Remove-AppxPackage
Get-AppxPackage -allusers *MicrosoftSolitaireCollection* | Remove-AppxPackage
Get-AppxPackage -allusers *Phone* | Remove-AppxPackage
Get-AppxPackage -allusers *WindowsSoundRecorder* | Remove-AppxPackage
Get-AppxPackage -allusers *People* | Remove-AppxPackage
Get-AppxPackage -allusers *Office* | Remove-AppxPackage
Get-AppxPackage -allusers *Getstarted* | Remove-AppxPackage
Get-AppxPackage -allusers *SkypeApp* | Remove-AppxPackage
Get-AppxPackage -allusers *WindowsMaps* | Remove-AppxPackage
Get-AppxPackage -allusers *OneNote* | Remove-AppxPackage
Get-AppxPackage -allusers *Reader* | Remove-AppxPackage
Get-AppxPackage -allusers *Messaging* | Remove-AppxPackage
Get-AppxPackage -allusers *CommsPhone* | Remove-AppxPackage
Get-AppxPackage -allusers *ConnectivityStore* | Remove-AppxPackage
Get-AppxPackage -allusers *Office.Sway* | Remove-AppxPackage
Get-AppxPackage -allusers *WindowsFeedbackHub* | Remove-AppxPackage
Get-AppxPackage -allusers *OneConnect* | Remove-AppxPackage
Get-AppxPackage -allusers *MicrosoftStickyNotes* | Remove-AppxPackage
Get-AppxPackage -allusers *GAMELOFTSA.Asphalt8Airborne* | Remove-AppxPackage
Get-AppxPackage -allusers *king.com.CandyCrushSodaSaga* | Remove-AppxPackage
Get-AppxPackage -allusers *StorePurchaseApp* | Remove-AppxPackage
Get-AppxPackage -allusers *Appconnector* | Remove-AppxPackage
Get-AppxPackage -allusers *Wallet* | Remove-AppxPackage 
Get-AppxPackage -allusers *AutodeskSketchBook* | Remove-AppxPackage
Get-AppxPackage -allusers *MarchofEmpires* | Remove-AppxPackage
Get-AppxPackage -allusers *Plex* | Remove-AppxPackage
Get-AppxPackage -allusers *Keeper* | Remove-AppxPackage
Get-AppxPackage -allusers *BubbleWitch3Saga* | Remove-AppxPackage
Get-AppxPackage -allusers *king.com* | Remove-AppxPackage
Get-AppxPackage -allusers *Advertising* | Remove-AppxPackage
Get-AppxPackage -allusers *MinecraftUWP* | Remove-AppxPackage
Get-AppxPackage -allusers *EclipseManager* | Remove-AppxPackage
Get-AppxPackage -allusers *ActiproSoftwareLLC* | Remove-AppxPackage
Get-AppxPackage -allusers *AdobeSystemsIncorporated.AdobePhotoshopExpress* | Remove-AppxPackage
Get-AppxPackage -allusers *Duolingo-LearnLanguagesforFree* | Remove-AppxPackage
Get-AppxPackage -allusers *PandoraMediaInc* | Remove-AppxPackage
Get-AppxPackage -allusers *CandyCrush* | Remove-AppxPackage
Get-AppxPackage -allusers *Wunderlist* | Remove-AppxPackage
Get-AppxPackage -allusers *Flipboard* | Remove-AppxPackage
Get-AppxPackage -allusers *Twitter* | Remove-AppxPackage
Get-AppxPackage -allusers *Facebook* | Remove-AppxPackage
Get-AppxPackage -allusers *Spotify* | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.549981C3F5F10 | Remove-AppxPackage
Get-AppXProvisionedPackage -online | Remove-AppxProvisionedPackage -online
