Get-AppxPackage -allusers *3d* | Remove-AppxPackage
Get-AppxPackage -allusers *xbox* | Remove-AppxPackage
Get-AppxPackage -allusers *bing* | Remove-AppxPackage
Get-AppxPackage -allusers *zune* | Remove-AppxPackage
Get-AppxPackage -allusers *community* | Remove-AppxPackage
Get-AppxPackage -allusers *solit* | Remove-AppxPackage
Get-AppxPackage -allusers *phone* | Remove-AppxPackage
Get-AppxPackage -allusers *soundrec* | Remove-AppxPackage
Get-AppxPackage -allusers *people* | Remove-AppxPackage
Get-AppxPackage -allusers *officehub* | Remove-AppxPackage
Get-AppxPackage -allusers *getstarted* | Remove-AppxPackage
Get-AppxPackage -allusers *skypeapp* | Remove-AppxPackage
Get-AppxPackage -allusers *windowsmaps* | Remove-AppxPackage
Get-AppxPackage -allusers *onenote* | Remove-AppxPackage
Get-AppxPackage -allusers *Reader* | Remove-AppxPackage
Get-AppxPackage -allusers *Messaging* | Remove-AppxPackage
Get-AppxPackage -allusers *CommsPhone* | Remove-AppxPackage
Get-AppxPackage -allusers *ConnectivityStore* | Remove-AppxPackage
Get-AppxPackage -allusers *Office.Sway* | Remove-AppxPackage
Get-AppxPackage -allusers *WindowsFeedbackHub* | Remove-AppxPackage
Get-AppxPackage -allusers *OneConnect* | Remove-AppxPackage
Get-AppxPackage -allusers *MicrosoftStickyNotes* | Remove-AppxPackage
Get-AppxPackage -allusers *GAMELOFTSA.Asphalt8Airborne* | Remove-AppxPackage
Get-AppxPackage -allusers *king.com.CandyCrushSodaSaga* | Remove-AppxPackage
Get-AppxPackage -allusers *StorePurchaseApp* | Remove-AppxPackage
Get-AppxPackage -allusers *Appconnector* | Remove-AppxPackage
Get-AppxPackage -allusers *Wallet* | Remove-AppxPackage
Get-AppxPackage -allusers *AutodeskSketchBook* | Remove-AppxPackage
Get-AppxPackage -allusers *MarchofEmpires* | Remove-AppxPackage
Get-AppxPackage -allusers *Plex* | Remove-AppxPackage
Get-AppxPackage -allusers *Keeper* | Remove-AppxPackage
Get-AppxPackage -allusers *BubbleWitch3Saga* | Remove-AppxPackage
Get-AppxPackage -allusers *king.com* | Remove-AppxPackage
Get-AppxPackage -allusers *Advertising* | Remove-AppxPackage
Get-AppxPackage -allusers *MinecraftUWP* | Remove-AppxPackage
Get-AppXProvisionedPackage -online | Remove-AppxProvisionedPackage -online
